version: '2'

services:
  prometheus:
    user: $UID
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/etc/prometheus:/etc/prometheus
      - ./prometheus/prometheus:/prometheus
    #command:
    #  - '--web.enable-lifecycle'
    links:
      - node0
      - node1
      - node2

  grafana:
    user: $UID
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    links:
      - prometheus
    volumes:
      - ./grafana/etc/grafana:/etc/grafana
      - ./grafana/var/lib/grafana:/var/lib/grafana
      - ./grafana/data:/data
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-azure-monitor-datasource, grafana-kubernetes-app
      - GF_PATH_DATA=/data
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_allow_sign_up=true
      - GF_USERS_allow_org_create=true
      - GF_ANALYTICS_reporting_enabled=false
      - GF_SMTP_enabled=false
      - GF_SMTP_host=postfix

  node0:
      user: $UID
      image: quay.io/prometheus/node-exporter:latest
      privileged: false
      restart: unless-stopped
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      #net: host
      command:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  node1:
      user: $UID
      image: prom/node-exporter:latest
      volumes:
        - ./node1/import:/import:ro
      command:
        - '--collector.textfile.directory=/import'

  node2:
      user: $UID
      image:  quay.io/prometheus/node-exporter:latest



#next: docker pull prom/blackbox-exporter
