version: '2'

services:
  prometheus:
    user: $PGUSER
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-central/etc/prometheus:/etc/prometheus
      - ./prometheus-central/db:/prometheus
    #command:
    #  - '--web.enable-lifecycle'
    links:
      - dc1-prometheus
      - dc2-prometheus
      - alertmanager

  dc1-prometheus:
    user: $PGUSER
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./datacenter-1/prometheus/etc/prometheus:/etc/prometheus
      - ./datacenter-1/prometheus/prometheus:/prometheus
    #command:
    #  - '--web.enable-lifecycle'
    links:
      - dc1-node0
      - dc1-node1
      - alertmanager

  dc2-prometheus:
    user: $PGUSER
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    volumes:
      - ./datacenter-2/prometheus/etc/prometheus:/etc/prometheus
      - ./datacenter-2/prometheus/prometheus:/prometheus
    #command:
    #  - '--web.enable-lifecycle'
    links:
      - dc2-node2
      - dc2-node3
      - alertmanager

  grafana:
    user: $PGUSER
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    links:
      - prometheus
      - dc1-prometheus
      - dc2-prometheus
      - mailserver

    volumes:
      - ./grafana/etc/grafana:/etc/grafana
      - ./grafana/var/lib/grafana:/var/lib/grafana
      - ./grafana/data:/data
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-azure-monitor-datasource,grafana-kubernetes-app,jdbranham-diagram-panel,snuids-trafficlights-panel,btplc-trend-box-panel
      - GF_PATH_DATA=/data
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_allow_sign_up=true
      - GF_USERS_allow_org_create=true
      - GF_ANALYTICS_reporting_enabled=false
      - GF_SMTP_enabled=false
      - GF_SMTP_host=postfix

  dc1-node0:
      user: $PGUSER
      image: quay.io/prometheus/node-exporter:latest
      privileged: false
      restart: unless-stopped
      volumes:
        - ./datacenter-1/node0/import:/import:ro
      #deactivated for windows docker hosts
      #  - /proc:/host/proc:ro
      #  - /sys:/host/sys:ro
      #  - /:/rootfs:ro
      ports:
        - "9100:9100"
      command:
        - '--collector.textfile.directory=/import'
      # deactivated for windows docker hosts
      #  - '--path.procfs=/host/proc'
      #  - '--path.sysfs=/host/sys'
      #  - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  dc1-node1:
      user: $PGUSER
      image: prom/node-exporter:latest
      volumes:
        - ./datacenter-1/node1/import:/import:ro
      ports:
        - "9101:9100"
      command:
        - '--collector.textfile.directory=/import'

  dc2-node2:
      user: $PGUSER
      image:  quay.io/prometheus/node-exporter:latest
      volumes:
        - ./datacenter-2/node2/import:/import:ro
      ports:
        - "9102:9100"
      command:
        - '--collector.textfile.directory=/import'

  dc2-node3:
      user: $PGUSER
      build: ./datacenter-2/node3CustomExporter
      privileged: false
      ports:
        - "9103:9100"


  alertmanager:
      user: $PGUSER
      image: prom/alertmanager:latest
      volumes:
        - ./alertmanager/etc/alertmanager:/etc/alertmanager:rw
      ports:
        - "9093:9093"
      links:
        - mailserver

  mailserver:
    image: greenmail/standalone:1.6.0-SNAPSHOT
    environment:
    # Enable GreenMail verbose mode
    - GREENMAIL_OPTS=-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled
  roundcube:
    image: roundcube/roundcubemail
    ports:
    - "9080:80"
    links:
      - mailserver
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_DEFAULT_PORT=3143
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=3025
    #volumes:
    #    - ./mailserver:/tmp/maildev:rw

#next: docker pull prom/blackbox-exporter
