version: '2'

services:
  prometheus:
    user: $UID
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/etc/prometheus:/etc/prometheus
      - ./prometheus/prometheus:/prometheus
    links:
      - node1
      - node2

  grafana:
    user: $UID
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    links:
      - prometheus
    volumes:
      - ./grafana/etc/grafana:/etc/grafana
      - ./grafana/var/lib/grafana:/var/lib/grafana
      - ./grafana/data:/data
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-azure-monitor-datasource, grafana-kubernetes-app
      - GF_PATH_DATA=/data
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_allow_sign_up=true
      - GF_USERS_allow_org_create=true
      - GF_ANALYTICS_reporting_enabled=false
      - GF_SMTP_enabled=false
      - GF_SMTP_host=postfix

  node1:
      user: $UID
      image: prom/node-exporter:latest
      #ports:
      #  - "9100:9100"
  node2:
      user: $UID
      image: prom/node-exporter:latest
      #ports:
      #  - "9100:9100"
          #volumes:
          #- ./prometheus/etc/prometheus:/etc/prometheus
          #- ./prometheus/prometheus:/prometheus
