  # rule for all messages which have tag "squad==storage"
  # rule 2.0
  - match:
      squad: storage
    receiver: web.hook
    continue: true

  # to call two independent receivers, we need two match handlers with same
  # condition and a continue expression
  - match:
      squad: storage
    receiver: admin-mail

    # rule for all messages which have tag "squad==storage" and
    # severity==critical
    # rule 2.1
    routes:
    - match:
        severity: critical
      receiver: team-dev-mails
