  # rule for all messages which have tag "service==files"
  # rule 2.0
  - match:
      service: files
    receiver: web.hook

    # rule for all messages which have tag "service==files" and
    # severity==critical
    # rule 2.1
    routes:
    - match:
        severity: critical
      receiver: team-dev-mails
